# data only container pattern
datadev:
  image: debian:jessie
  volumes:
    - .:/app
    - ./data/dev:/data

db:
  image: postgres:10
  environment:
    - POSTGRES_USER=turtleapp
    - POSTGRES_PASSWORD=turtleapp
  ports:
    - "5432"

cache:
  image: memcached:1.4

nginx:
  image: muccg/nginx-uwsgi:1.10
  ports:
    - "8443:443"
    - "8080:80"
  volumes:
    - ./data/nginx:/data

runserver:
  image: muccg/turtle-dev
  environment:
    - DBUSER=turtleapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
  ports:
    - "3000:3000"
    - "3001:3001"

uwsgi:
  image: muccg/turtle-dev
  command: uwsgi
  environment:
    - DBUSER=turtleapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_RUNSERVER=1
    # note: important to wait for runserver in dev as both will attempt to syncdb etc
  ports:
    - "9000:9000"
    - "9001:9001"
    - "9100:9100"
    - "9101:9101"
