version: '2'
services:

  base:
    build:
      context: ./
      dockerfile: Dockerfile-base
      args:
        http_proxy:
    image: muccg/turtle-base

  builder:
    build:
      context: ./
      dockerfile: Dockerfile-build
      args:
        ARG_GIT_TAG: ${GIT_TAG}
        http_proxy:
    image: muccg/turtle-builder
    command: releasetarball
    network_mode: host
    environment:
        BUILD_VERSION:
        GIT_BRANCH:
        PIP_INDEX_URL:
        PIP_TRUSTED_HOST:
        NO_PROXY:
    volumes:
      - ./build:/data

  dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        ARG_PIP_INDEX_URL: ${PIP_INDEX_URL}
        ARG_PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
    image: muccg/turtle-dev
    volumes:
      - .:/app

  prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        ARG_GIT_TAG: ${GIT_TAG}
    image: muccg/turtle:${GIT_TAG}

  lint:
    image: muccg/linter:python3
    working_dir: /data
    volumes:
        - ./:/data
