#
FROM muccg/python-base:3.6-debian-8
MAINTAINER https://github.com/muccg/

# Note: The project is referred to as 'turtle', git repo is 'turtleweb' and the settings module is 'kindred'. 
ENV PROJECT_NAME turtle
ENV PROJECT_SOURCE git@github.com:muccg/turtleweb.git
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV MONGO_DB_PREFIX=prod_
ENV DJANGO_SETTINGS_MODULE kindred.settings
ENV NODE_MODULES /npm/node_modules

RUN env | sort

# Project specific deps
# temporary: fix issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866729
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man7 && apt-get update && apt-get install -y --no-install-recommends \
  liblcms2-2 \
  libfreetype6 \
  libjpeg62-turbo \
  libopenjpeg5 \
  libpcre3 \
  libpq5 \
  libtiff5 \
  libwebp5 \
  libxml2 \
  libxslt1.1 \
  mime-support \
  nodejs-legacy \
  zlib1g \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/sh"]
