#!/usr/bin/env python3
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "kindred.settings")
    os.environ.setdefault("APP_INSTANCE", "turtle")

    import django
    django.setup()

    # Override default port for `runserver` command
    import django.core.management.commands.runserver as runserver_module
    from django.core.management.commands.runserver import Command as runserver
    runserver_module.DEFAULT_PORT = "8001"  # Django 1.8
    runserver.default_port = "8001"  # Django 1.9

    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
